language: go

install:
 - export PATH=$HOME/gopath/bin:$PATH
 - go get golang.org/x/tools/cmd/cover
 - go get -v github.com/axw/gocov
 - go install github.com/axw/gocov/gocov

script:
 - gocov test | gocov report